import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cfg=window.DLM_CONFIG;
if(cfg){
  const supabase=createClient(cfg.url,cfg.key);
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const headers=['title','portfolio','campus','data_center','project_contract','organization','document_type','discipline','drawing_type','level','stage','serial_number','document_number','legacy_source_note','comments'];
  let role='viewer',lookups={},rows=[],validation=[];
  const canImport=()=>['document_controller','admin'].includes(role);
  const active=n=>(lookups[n]||[]).filter(x=>x.is_active!==false);
  const norm=v=>String(v||'').trim().toUpperCase();
  const byCode=(n,c)=>active(n).find(x=>norm(x.code)===norm(c));
  function notify(m,e=false){const el=$('toast');if(!el)return;el.textContent=m;el.className=`toast show ${e?'error':'success'}`;clearTimeout(notify.t);notify.t=setTimeout(()=>el.className='toast',4000)}
  function q(v){return `"${String(v??'').replaceAll('"','""')}"`}
  function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function parseCsv(text){text=text.replace(/^\uFEFF/,'');const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else{if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell);out.push(row);row=[];cell='';}else if(ch!=='\r')cell+=ch;}}if(cell.length||row.length){row.push(cell);out.push(row);}return out.filter(r=>r.some(x=>String(x).trim()!==''));}
  function csvToObjects(text){const parsed=parseCsv(text);if(!parsed.length)throw new Error('CSV file is empty.');const hs=parsed[0].map(x=>x.trim().toLowerCase());const missing=headers.filter(h=>!hs.includes(h));if(missing.length)throw new Error(`Missing columns: ${missing.join(', ')}`);return parsed.slice(1).map((r,i)=>{const obj={};hs.forEach((h,j)=>obj[h]=(r[j]??'').trim());obj.__row=i+2;return obj;});}
  function buildNumber(r){if(r.document_number)return r.document_number;return `${norm(r.portfolio)}-${norm(r.campus)}-${norm(r.data_center)}-${norm(r.project_contract)}-${norm(r.organization)}-${norm(r.document_type)}-${norm(r.discipline)}-${norm(r.drawing_type)}${norm(r.level)}-${String(Number(r.serial_number)).padStart(6,'0')}`}
  async function validateRows(){const {data:existing,error}=await supabase.from('drawing_register_v').select('document_number,document_type_code,discipline_code,serial_number');if(error)throw error;const docs=new Set((existing||[]).map(x=>norm(x.document_number)));const serials=new Set((existing||[]).map(x=>`${norm(x.document_type_code)}|${norm(x.discipline_code)}|${Number(x.serial_number)}`));const seenDocs=new Set(),seenSerials=new Set();validation=rows.map(r=>{const issues=[];const req=['title','portfolio','campus','data_center','project_contract','organization','document_type','discipline','drawing_type','level','serial_number'];req.forEach(k=>{if(!r[k])issues.push(`${k} is required`)});const serial=Number(r.serial_number);if(!Number.isInteger(serial)||serial<1||serial>999999)issues.push('serial_number must be 1-999999');const maps={portfolio:'portfolios',campus:'campus_plots',data_center:'data_centers',project_contract:'project_contracts',organization:'organizations',document_type:'document_types',discipline:'disciplines',drawing_type:'drawing_types',level:'levels',stage:'stages'};for(const[k,n]of Object.entries(maps)){if(r[k]&&!byCode(n,r[k]))issues.push(`Unknown/inactive ${k}: ${r[k]}`)}const dt=byCode('document_types',r.document_type),dr=byCode('drawing_types',r.drawing_type);if(dt?.category==='document')issues.push('document_type must be drawing or DDE');if(dt&&dr){const expected=dt.category==='dde'?'dde':'drawing';if(dr.type_kind!==expected)issues.push(`drawing_type must be ${expected}`)}const doc=buildNumber(r),du=norm(doc),sk=`${norm(r.document_type)}|${norm(r.discipline)}|${serial}`;if(docs.has(du))issues.push('Document number already exists');if(serials.has(sk))issues.push('Serial already exists for Document Type + Discipline');if(seenDocs.has(du))issues.push('Duplicate document number inside CSV');if(seenSerials.has(sk))issues.push('Duplicate serial scope inside CSV');seenDocs.add(du);seenSerials.add(sk);return{...r,__doc:doc,__issues:issues,__valid:issues.length===0,__imported:false};});renderPreview();}
  function renderPreview(){const good=validation.filter(x=>x.__valid).length,bad=validation.filter(x=>!x.__valid&&!x.__imported).length,done=validation.filter(x=>x.__imported).length;$('bulkSummary').innerHTML=`<strong>${validation.length}</strong> rows · <strong>${good}</strong> valid · <strong>${bad}</strong> errors${done?` · <strong>${done}</strong> imported`:''}`;$('bulkImportBtn').disabled=!good;$('downloadBulkErrors').disabled=!bad;$('bulkPreviewBody').innerHTML=validation.map(r=>`<tr><td>${r.__row}</td><td class="doc-number">${esc(r.__doc)}</td><td>${esc(r.title)}</td><td>${String(r.serial_number||'').padStart(6,'0')}</td><td>${r.__imported?'<span class="badge active">Imported</span>':r.__valid?'<span class="badge active">Valid</span>':`<span class="badge cancelled">Error</span><div class="tiny muted">${esc(r.__issues.join('; '))}</div>`}</td></tr>`).join('');}
  function errorReport(){const bad=validation.filter(x=>!x.__valid&&!x.__imported);if(!bad.length)return notify('No validation/import errors to export');const cols=['row','document_number','title','document_type','discipline','serial_number','errors'];const body=bad.map(r=>[r.__row,r.__doc,r.title,r.document_type,r.discipline,r.serial_number,r.__issues.join(' | ')].map(q).join(','));download(`drawing-import-errors-${new Date().toISOString().slice(0,10)}.csv`,[cols.join(','),...body].join('\r\n'))}
  async function importValid(){const valid=validation.filter(x=>x.__valid);if(!valid.length)return;const btn=$('bulkImportBtn');btn.disabled=true;let ok=0,fail=0;for(let i=0;i<valid.length;i++){const r=valid[i];btn.textContent=`Importing ${i+1}/${valid.length}…`;const p={p_title:r.title,p_portfolio:norm(r.portfolio),p_campus:norm(r.campus),p_data_center:norm(r.data_center),p_project_contract:norm(r.project_contract),p_organization:norm(r.organization),p_document_type:norm(r.document_type),p_discipline:norm(r.discipline),p_drawing_type:norm(r.drawing_type),p_level:norm(r.level),p_serial:Number(r.serial_number),p_stage:r.stage?norm(r.stage):null,p_comments:r.comments||null,p_document_number:r.document_number||null,p_legacy_source_note:r.legacy_source_note||'Bulk CSV legacy import'};const {error}=await supabase.rpc('import_existing_drawing',p);r.__valid=false;if(error){fail++;r.__issues=[error.message];}else{ok++;r.__imported=true;r.__issues=[];}}btn.textContent='Import Valid Rows';renderPreview();notify(`${ok} imported · ${fail} failed · ${validation.filter(x=>!x.__valid&&!x.__imported).length} unresolved errors`,!!fail);}
  function template(){const blank=headers.map(()=>q('')).join(',');download('drawing-log-legacy-import-template.csv',[headers.join(','),blank].join('\r\n'))}
  async function exportRegister(){const {data,error}=await supabase.from('drawing_register_v').select('*').order('created_at',{ascending:true});if(error)return notify(error.message,true);const body=(data||[]).map(r=>[r.title,r.portfolio_code||r.portfolio,r.campus_plot_code||r.campus,r.data_center_code||r.data_center,r.project_contract_code||r.project_contract,r.organization_code||r.organization,r.document_type_code,r.discipline_code,r.drawing_type_code,r.level_code,r.stage_code||'',r.serial_number,r.document_number,r.legacy_source_note||'',r.comments||''].map(q).join(','));download(`drawing-register-import-schema-${new Date().toISOString().slice(0,10)}.csv`,[headers.join(','),...body].join('\r\n'))}
  function inject(){if($('bulkCsvPanel'))return true;const page=$('legacyPage');if(!page)return false;const panel=document.createElement('div');panel.id='bulkCsvPanel';panel.className='panel section-gap';panel.innerHTML=`<div class="panel-head"><div><h3>Bulk CSV Import / Export</h3><p class="muted">Controlled historical drawing import with case-normalized duplicate checks and downloadable error reporting.</p></div><div class="form-actions"><button id="downloadBulkTemplate" class="btn secondary" type="button">Download Blank Template</button><button id="exportBulkSchema" class="btn secondary" type="button">Export Register (Import Schema)</button></div></div><div class="toolbar"><input id="bulkCsvFile" type="file" accept=".csv,text/csv" /><button id="validateBulkBtn" class="btn primary" type="button" disabled>Validate CSV</button><button id="bulkImportBtn" class="btn primary" type="button" disabled>Import Valid Rows</button><button id="downloadBulkErrors" class="btn secondary" type="button" disabled>Download Error Report</button></div><div id="bulkSummary" class="muted small-text">Choose a CSV file to begin.</div><div class="table-wrap section-gap"><table><thead><tr><th>Row</th><th>Document Number</th><th>Title</th><th>Serial</th><th>Validation</th></tr></thead><tbody id="bulkPreviewBody"></tbody></table></div>`;page.appendChild(panel);$('downloadBulkTemplate').addEventListener('click',template);$('exportBulkSchema').addEventListener('click',exportRegister);$('downloadBulkErrors').addEventListener('click',errorReport);$('bulkCsvFile').addEventListener('change',async e=>{validation=[];$('bulkPreviewBody').innerHTML='';$('downloadBulkErrors').disabled=true;const f=e.target.files?.[0];if(!f){$('validateBulkBtn').disabled=true;return}try{rows=csvToObjects(await f.text());$('validateBulkBtn').disabled=false;$('bulkSummary').textContent=`${rows.length} rows loaded. Click Validate CSV.`}catch(err){notify(err.message,true);$('validateBulkBtn').disabled=true}});$('validateBulkBtn').addEventListener('click',()=>validateRows().catch(e=>notify(e.message,true)));$('bulkImportBtn').addEventListener('click',importValid);return true;}
  async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data}=await supabase.rpc('current_user_role');role=data||'viewer';if(!canImport())return;const names=['portfolios','campus_plots','data_centers','project_contracts','organizations','document_types','disciplines','drawing_types','levels','stages'];const rs=await Promise.all(names.map(async n=>{const {data,error}=await supabase.from(n).select('*').order('code');if(error)throw error;return[n,data||[]]}));lookups=Object.fromEntries(rs);for(let i=0;i<20&&!inject();i++)await new Promise(r=>setTimeout(r,150));}
  setTimeout(()=>init().catch(e=>notify(e.message,true)),150);
}
