import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cfg=window.DLM_CONFIG;
if(cfg){
  const supabase=createClient(cfg.url,cfg.key);
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const headers=['title','portfolio','campus','data_center','project_contract','organization','document_type','discipline','stage','drawing_type','level','serial_number','document_number','legacy_source_note','comments'];
  let role='viewer',lookups={},rows=[],validation=[];
  const canImport=()=>['document_controller','admin'].includes(role);
  const active=n=>(lookups[n]||[]).filter(x=>x.is_active!==false);
  const norm=v=>String(v||'').trim().toUpperCase();
  const byCode=(n,c)=>active(n).find(x=>norm(x.code)===norm(c));
  function notify(m,e=false){const el=$('toast');if(!el)return;el.textContent=m;el.className=`toast show ${e?'error':'success'}`;setTimeout(()=>el.className='toast',4000)}
  function q(v){return `"${String(v??'').replaceAll('"','""')}"`}
  function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function parseCsv(text){text=text.replace(/^\uFEFF/,'');const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else{if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell);out.push(row);row=[];cell='';}else if(ch!=='\r')cell+=ch;}}if(cell.length||row.length){row.push(cell);out.push(row);}return out.filter(r=>r.some(x=>String(x).trim()!==''));}
  function csvToObjects(text){const parsed=parseCsv(text);if(!parsed.length)throw new Error('CSV file is empty.');const hs=parsed[0].map(x=>x.trim().toLowerCase());const missing=headers.filter(h=>!hs.includes(h));if(missing.length)throw new Error(`Missing columns: ${missing.join(', ')}`);return parsed.slice(1).map((r,i)=>{const obj={};hs.forEach((h,j)=>obj[h]=(r[j]??'').trim());obj.__row=i+2;return obj;});}
  function buildNumber(r){const serial=Number(r.serial_number);return `${norm(r.portfolio)}-${norm(r.campus)}-${norm(r.data_center)}-${norm(r.project_contract)}-${norm(r.organization)}-${norm(r.document_type)}-${norm(r.discipline)}-${norm(r.stage)}-${norm(r.drawing_type)}${norm(r.level)}-${String(serial).padStart(6,'0')}`;}
  async function validateRows(){
    const {data:existing,error}=await supabase.from('drawing_register_v').select('document_number');if(error)throw error;
    const docs=new Set((existing||[]).map(x=>norm(x.document_number)));
    const seenDocs=new Set();
    validation=rows.map(r=>{
      const issues=[];const req=['title','portfolio','campus','data_center','project_contract','organization','document_type','discipline','stage','drawing_type','level','serial_number'];req.forEach(k=>{if(!String(r[k]||'').trim())issues.push(`${k} is required`)});
      const serial=Number(r.serial_number);if(!Number.isInteger(serial)||serial<1||serial>999999)issues.push('serial_number must be 1-999999');
      const maps={portfolio:'portfolios',campus:'campus_plots',data_center:'data_centers',project_contract:'project_contracts',organization:'organizations',document_type:'document_types',discipline:'disciplines',stage:'stages',drawing_type:'drawing_types',level:'levels'};
      for(const[k,n]of Object.entries(maps)){if(r[k]&&!byCode(n,r[k]))issues.push(`Unknown/inactive ${k}: ${r[k]}`)}
      const dt=byCode('document_types',r.document_type),dr=byCode('drawing_types',r.drawing_type);if(dt?.category==='document')issues.push('document_type must be drawing or DDE');if(dt&&dr){const expected=dt.category==='dde'?'dde':'drawing';if(dr.type_kind!==expected)issues.push(`drawing_type must be ${expected}`)}
      const expectedDoc=buildNumber(r),provided=norm(r.document_number),doc=provided||expectedDoc,du=norm(doc);
      if(provided&&provided!==norm(expectedDoc))issues.push(`document_number does not match fields; expected ${expectedDoc}`);
      if(docs.has(du))issues.push('Document number already exists');
      if(seenDocs.has(du))issues.push('Duplicate document number inside CSV');
      seenDocs.add(du);
      return{...r,__doc:doc,__expected:expectedDoc,__issues:issues,__valid:issues.length===0};
    });renderPreview();
  }
  function renderPreview(){const good=validation.filter(x=>x.__valid).length,bad=validation.length-good;$('bulkSummary').innerHTML=`<strong>${validation.length}</strong> rows · <strong>${good}</strong> valid · <strong>${bad}</strong> with errors`;$('bulkImportBtn').disabled=!good;$('bulkErrorReportBtn').disabled=!bad;$('bulkPreviewBody').innerHTML=validation.map(r=>`<tr><td>${r.__row}</td><td class="doc-number">${esc(r.__doc)}</td><td>${esc(r.title)}</td><td>${String(r.serial_number).padStart(6,'0')}</td><td>${r.__valid?'<span class="badge active">Valid</span>':`<span class="badge cancelled">Error</span><div class="tiny muted">${esc(r.__issues.join('; '))}</div>`}</td></tr>`).join('');}
  async function importValid(){const valid=validation.filter(x=>x.__valid);if(!valid.length)return;const btn=$('bulkImportBtn');btn.disabled=true;let ok=0,fail=0;for(let i=0;i<valid.length;i++){const r=valid[i];btn.textContent=`Importing ${i+1}/${valid.length}…`;const p={p_title:r.title,p_portfolio:norm(r.portfolio),p_campus:norm(r.campus),p_data_center:norm(r.data_center),p_project_contract:norm(r.project_contract),p_organization:norm(r.organization),p_document_type:norm(r.document_type),p_discipline:norm(r.discipline),p_drawing_type:norm(r.drawing_type),p_level:norm(r.level),p_serial:Number(r.serial_number),p_stage:norm(r.stage),p_comments:r.comments||null,p_document_number:r.__doc,p_legacy_source_note:r.legacy_source_note||'Bulk CSV legacy import'};const {error}=await supabase.rpc('import_existing_drawing',p);if(error){fail++;r.__valid=false;r.__issues=[error.message];}else ok++;}btn.textContent='Import Valid Rows';notify(`${ok} imported · ${fail} failed`,!!fail);await validateRows();}
  function template(){download('drawing-log-legacy-import-template.csv',headers.join(','));}
  function errorReport(){const bad=validation.filter(x=>!x.__valid);if(!bad.length)return;const cols=['row','document_number','title','errors'];const body=bad.map(r=>[r.__row,r.__doc,r.title,r.__issues.join(' | ')].map(q).join(','));download(`drawing-import-errors-${new Date().toISOString().slice(0,10)}.csv`,[cols.join(','),...body].join('\r\n'));}
  async function exportRegister(){const {data,error}=await supabase.from('drawing_register_v').select('*').order('created_at',{ascending:true});if(error)return notify(error.message,true);const body=(data||[]).map(r=>[r.title,r.portfolio_code||r.portfolio,r.campus_plot_code||r.campus,r.data_center_code||r.data_center,r.project_contract_code||r.project_contract,r.organization_code||r.organization,r.document_type_code,r.discipline_code,r.stage_code||'',r.drawing_type_code,r.level_code,r.serial_number,r.document_number,r.legacy_source_note||'',r.comments||''].map(q).join(','));download(`drawing-register-import-schema-${new Date().toISOString().slice(0,10)}.csv`,[headers.join(','),...body].join('\r\n'));}
  function inject(){if($('bulkCsvPanel'))return true;const page=$('legacyPage');if(!page)return false;const panel=document.createElement('div');panel.id='bulkCsvPanel';panel.className='panel section-gap';panel.innerHTML=`<div class="panel-head"><div><h3>Bulk CSV Import / Export</h3><p class="muted">Controlled historical drawing import. Stage is mandatory and is part of the drawing number. Uniqueness is checked on the complete document number; serials may repeat when another controlled field differs.</p></div><div class="form-actions"><button id="downloadBulkTemplate" class="btn secondary" type="button">Download CSV Template</button><button id="exportBulkSchema" class="btn secondary" type="button">Export Register (Import Schema)</button></div></div><div class="toolbar"><input id="bulkCsvFile" type="file" accept=".csv,text/csv" /><button id="validateBulkBtn" class="btn primary" type="button" disabled>Validate CSV</button><button id="bulkImportBtn" class="btn primary" type="button" disabled>Import Valid Rows</button><button id="bulkErrorReportBtn" class="btn secondary" type="button" disabled>Download Error Report</button></div><div id="bulkSummary" class="muted small-text">Choose a CSV file to begin.</div><div class="table-wrap section-gap"><table><thead><tr><th>Row</th><th>Document Number</th><th>Title</th><th>Serial</th><th>Validation</th></tr></thead><tbody id="bulkPreviewBody"></tbody></table></div>`;page.appendChild(panel);$('downloadBulkTemplate').onclick=template;$('exportBulkSchema').onclick=exportRegister;$('bulkErrorReportBtn').onclick=errorReport;$('bulkCsvFile').onchange=async e=>{validation=[];$('bulkPreviewBody').innerHTML='';const f=e.target.files?.[0];if(!f){$('validateBulkBtn').disabled=true;return}try{rows=csvToObjects(await f.text());$('validateBulkBtn').disabled=false;$('bulkSummary').textContent=`${rows.length} rows loaded. Click Validate CSV.`}catch(err){notify(err.message,true);$('validateBulkBtn').disabled=true}};$('validateBulkBtn').onclick=()=>validateRows().catch(e=>notify(e.message,true));$('bulkImportBtn').onclick=importValid;return true;}
  async function init(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data}=await supabase.rpc('current_user_role');role=data||'viewer';if(!canImport())return;const names=['portfolios','campus_plots','data_centers','project_contracts','organizations','document_types','disciplines','drawing_types','levels','stages'];const rs=await Promise.all(names.map(async n=>{const {data,error}=await supabase.from(n).select('*').order('code');if(error)throw error;return[n,data||[]]}));lookups=Object.fromEntries(rs);for(let i=0;i<20&&!inject();i++)await new Promise(r=>setTimeout(r,150));}
  setTimeout(()=>init().catch(e=>notify(e.message,true)),150);
}
