import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.DLM_CONFIG;
if(cfg){
const supabase=createClient(cfg.url,cfg.key),$=id=>document.getElementById(id);
let role='viewer',plans=[],rows=[],drawings=[],lookups={};
const rank={viewer:0,editor:1,document_controller:2,admin:3},can=r=>(rank[role]||0)>=(rank[r]||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=(m,e=false)=>{const t=$('toast');if(!t)return;t.textContent=m;t.className=`toast show ${e?'error':'success'}`;clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',4000)};
const fmt=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString():'—';
function injectStyles(){if($('planningStyles'))return;const s=document.createElement('style');s.id='planningStyles';s.textContent=`
.plan-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.plan-tab.active{background:#162a46;color:#fff}.plan-stat-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin:14px 0}.plan-stat{padding:14px}.plan-stat span{display:block;font-size:11px;color:#748094}.plan-stat strong{font-size:22px}.plan-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.plan-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.plan-form .span-2{grid-column:span 2}.tracking-chip{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:700;background:#eef2f7}.tracking-chip.overdue,.tracking-chip.delivered-late{background:#fde8e8;color:#982a2a}.tracking-chip.due-soon{background:#fff3cf;color:#8a6500}.tracking-chip.on-track,.tracking-chip.delivered-on-time,.tracking-chip.delivered-early{background:#e7f6ed;color:#21633a}.planning-actions{display:flex;gap:6px;flex-wrap:wrap}.plan-card{padding:12px;border:1px solid #e5e9ef;border-radius:10px;margin-bottom:8px}.plan-card strong{display:block}.plan-sub{font-size:11px;color:#707b8d}.planning-table{max-height:520px;overflow:auto}.calendar-row{display:grid;grid-template-columns:100px 1fr 120px 120px;gap:10px;padding:10px 0;border-bottom:1px solid #edf0f4;align-items:center}@media(max-width:1100px){.plan-stat-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.plan-stat-grid,.plan-grid,.plan-form{grid-template-columns:1fr}.plan-form .span-2{grid-column:span 1}.calendar-row{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function ensurePage(){if($('planningPage'))return;injectStyles();const nav=document.querySelector('.nav');const btn=document.createElement('button');btn.className='nav-item';btn.dataset.page='planning';btn.textContent='Information Delivery';btn.onclick=()=>showPlanning();nav?.insertBefore(btn,nav.querySelector('[data-page="codes"]'));
const page=document.createElement('section');page.id='planningPage';page.className='page hidden';page.innerHTML=`<div class="plan-tabs"><button class="btn secondary plan-tab active" data-tab="overview">Overview</button><button class="btn secondary plan-tab" data-tab="plans">MIDP / TIDP</button><button class="btn secondary plan-tab" data-tab="deliverables">Deliverables</button><button class="btn secondary plan-tab" data-tab="calendar">Delivery Calendar</button></div>
<div id="planOverview" class="plan-pane"><div class="plan-stat-grid"><div class="panel plan-stat"><span>Total Deliverables</span><strong id="pTotal">0</strong></div><div class="panel plan-stat"><span>On Track</span><strong id="pOnTrack">0</strong></div><div class="panel plan-stat"><span>Due Soon</span><strong id="pDueSoon">0</strong></div><div class="panel plan-stat"><span>Overdue</span><strong id="pOverdue">0</strong></div><div class="panel plan-stat"><span>Delivered On Time</span><strong id="pOnTime">0</strong></div><div class="panel plan-stat"><span>Delivered Late</span><strong id="pLate">0</strong></div></div><div class="plan-grid"><div class="panel"><div class="panel-head"><h3>Plan Summary</h3><button id="pRefresh" class="btn secondary">Refresh</button></div><div id="planSummary"></div></div><div class="panel"><h3>Attention Required</h3><div id="attentionList"></div></div></div></div>
<div id="planPlans" class="plan-pane hidden"><div class="plan-grid"><div class="panel"><div class="panel-head"><div><h3>MIDP / TIDP</h3><p class="muted">MIDP is the master plan. Each TIDP is linked to a MIDP.</p></div></div><div id="plansList"></div></div><form id="newPlanForm" class="panel plan-form controller-only"><div class="span-2"><h3>Create Delivery Plan</h3></div><label>Type<select id="planType"><option>MIDP</option><option>TIDP</option></select></label><label>Code<input id="planCode" required placeholder="e.g. MIDP-001" /></label><label class="span-2">Name<input id="planName" required /></label><label id="parentPlanLabel" class="span-2 hidden">Parent MIDP<select id="parentPlan"></select></label><label>Organization<select id="planOrg"></select></label><label>Status<input value="active" disabled /></label><label class="span-2">Description<textarea id="planDesc" rows="3"></textarea></label><button class="btn primary span-2" type="submit">Create Plan</button></form></div></div>
<div id="planDeliverables" class="plan-pane hidden"><div class="panel"><div class="panel-head"><div><h3>Information Deliverables</h3><p class="muted">Baseline date is frozen. Current planned date may change only with a recorded reason.</p></div><div><select id="deliverablePlanFilter"><option value="">All plans</option></select></div></div><div class="table-wrap planning-table"><table><thead><tr><th>Plan</th><th>Document / Deliverable</th><th>Discipline</th><th>Baseline</th><th>Current</th><th>Actual</th><th>Revision</th><th>Tracking</th><th>Approval</th><th></th></tr></thead><tbody id="deliverableBody"></tbody></table></div></div><form id="newDeliverableForm" class="panel plan-form controller-only section-gap"><div class="span-2"><h3>Add Deliverable</h3><p class="muted">You can link an existing drawing now or create a planned deliverable before the drawing number exists.</p></div><label>Plan<select id="delPlan" required></select></label><label>Baseline Due Date<input id="delBaseline" type="date" required /></label><label class="span-2">Link Existing Drawing<select id="delDrawing"><option value="">Planned item — no drawing yet</option></select></label><label class="span-2">Deliverable Title<input id="delTitle" required /></label><label>Discipline<select id="delDiscipline"></select></label><label>Document Type<select id="delDocType"></select></label><label>Responsible Organization<select id="delOrg"></select></label><label>Notes<input id="delNotes" /></label><button class="btn primary span-2" type="submit">Add Deliverable</button></form></div>
<div id="planCalendar" class="plan-pane hidden"><div class="panel"><div class="panel-head"><div><h3>Delivery Calendar</h3><p class="muted">Open deliverables ordered by current planned delivery date.</p></div></div><div id="calendarList"></div></div></div>`;
document.querySelector('main.main')?.appendChild(page);
page.querySelectorAll('.plan-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('pRefresh').onclick=loadAll;$('planType').onchange=toggleParent;$('newPlanForm').onsubmit=createPlan;$('newDeliverableForm').onsubmit=createDeliverable;$('deliverablePlanFilter').onchange=renderDeliverables;$('delDrawing').onchange=fillFromDrawing;}
function showPlanning(){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$('planningPage').classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page==='planning'));$('pageTitle').textContent='Information Delivery';$('pageSubtitle').textContent='MIDP / TIDP planning and delivery tracking aligned to ISO 19650 principles';loadAll()}
function switchTab(name){document.querySelectorAll('.plan-pane').forEach(x=>x.classList.add('hidden'));$(`plan${name[0].toUpperCase()+name.slice(1)}`).classList.remove('hidden');document.querySelectorAll('.plan-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}
const option=(arr,ph,fn=x=>`${x.code} — ${x.name}`)=>`<option value="">${ph}</option>`+arr.map(x=>`<option value="${esc(x.id??x.code)}">${esc(fn(x))}</option>`).join('');
async function bootstrap(){ensurePage();const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:r}=await supabase.rpc('current_user_role');role=r||'viewer';document.querySelectorAll('.controller-only').forEach(x=>x.classList.toggle('hidden',!can('document_controller')));await loadLookups();}
async function loadLookups(){const names=['organizations','disciplines','document_types'];const results=await Promise.all(names.map(async n=>{const {data}=await supabase.from(n).select('*').eq('is_active',true).order('code');return[n,data||[]]}));lookups=Object.fromEntries(results);$('planOrg').innerHTML=option(lookups.organizations,'None');$('delOrg').innerHTML=option(lookups.organizations,'None');$('delDiscipline').innerHTML=option(lookups.disciplines,'Select…');$('delDocType').innerHTML=option(lookups.document_types,'Select…');}
async function loadAll(){try{const [{data:p,error:pe},{data:r,error:re},{data:d,error:de}]=await Promise.all([supabase.from('information_delivery_plans').select('*').order('plan_code'),supabase.from('information_delivery_register_v').select('*').order('current_due_date'),supabase.from('drawing_register_v').select('id,document_number,title,discipline_code,document_type_code,status').eq('status','active').order('document_number')]);if(pe||re||de)throw(pe||re||de);plans=p||[];rows=r||[];drawings=d||[];populateSelectors();renderAll()}catch(e){toast(e.message||'Could not load planning data',true)}}
function populateSelectors(){const active=plans.filter(x=>['draft','active'].includes(x.status));$('parentPlan').innerHTML=option(active.filter(x=>x.plan_type==='MIDP'),'Select MIDP…',x=>`${x.plan_code} — ${x.plan_name}`);$('delPlan').innerHTML=option(active,'Select plan…',x=>`${x.plan_code} — ${x.plan_name}`);$('deliverablePlanFilter').innerHTML=option(plans,'All plans',x=>`${x.plan_code} — ${x.plan_name}`);$('delDrawing').innerHTML=option(drawings,'Planned item — no drawing yet',x=>`${x.document_number} — ${x.title}`)}
function renderAll(){renderStats();renderPlans();renderDeliverables();renderCalendar()}
function renderStats(){const c=s=>rows.filter(x=>x.tracking_status===s).length;$('pTotal').textContent=rows.length;$('pOnTrack').textContent=c('On Track');$('pDueSoon').textContent=c('Due Soon');$('pOverdue').textContent=c('Overdue');$('pOnTime').textContent=c('Delivered On Time')+c('Delivered Early');$('pLate').textContent=c('Delivered Late');$('planSummary').innerHTML=plans.length?plans.map(p=>{const n=rows.filter(r=>r.plan_id===p.id).length;return`<div class="plan-card"><strong>${esc(p.plan_code)} · ${esc(p.plan_type)}</strong><div>${esc(p.plan_name)}</div><div class="plan-sub">${n} deliverable${n===1?'':'s'} · ${esc(p.status)}</div></div>`}).join(''):'<div class="muted">No plans yet.</div>';const a=rows.filter(r=>['Overdue','Due Soon','Delivered Late'].includes(r.tracking_status)).slice(0,12);$('attentionList').innerHTML=a.length?a.map(r=>`<div class="plan-card"><strong>${esc(r.document_number||r.deliverable_title)}</strong><div class="plan-sub">${esc(r.plan_code)} · ${fmt(r.current_due_date)} · ${esc(r.tracking_status)}</div></div>`).join(''):'<div class="muted">Nothing requires attention.</div>'}
function renderPlans(){$('plansList').innerHTML=plans.length?plans.map(p=>`<div class="plan-card"><strong>${esc(p.plan_code)} · ${esc(p.plan_type)}</strong><div>${esc(p.plan_name)}</div><div class="plan-sub">${p.parent_plan_id?'Linked MIDP: '+esc(plans.find(x=>x.id===p.parent_plan_id)?.plan_code||'—'):'Master plan'} · ${esc(p.organization_code||'No organization')} · ${esc(p.status)}</div>${p.description?`<div class="plan-sub">${esc(p.description)}</div>`:''}</div>`).join(''):'<div class="muted">Create a MIDP first, then add TIDPs beneath it.</div>'}
const chip=s=>`<span class="tracking-chip ${String(s).toLowerCase().replaceAll(' ','-')}">${esc(s)}</span>`;
function renderDeliverables(){const f=$('deliverablePlanFilter').value,list=f?rows.filter(r=>r.plan_id===f):rows;$('deliverableBody').innerHTML=list.length?list.map(r=>`<tr><td>${esc(r.plan_code)}</td><td><strong>${esc(r.document_number||r.deliverable_title)}</strong><div class="tiny muted">${esc(r.deliverable_title)}</div></td><td>${esc(r.discipline_code||'—')}</td><td>${fmt(r.baseline_due_date)}</td><td>${fmt(r.current_due_date)}${r.plan_variance_days?`<div class="tiny muted">${r.plan_variance_days>0?'+':''}${r.plan_variance_days}d vs baseline</div>`:''}</td><td>${fmt(r.actual_delivery_date)}</td><td>${esc(r.delivered_revision||'—')}</td><td>${chip(r.tracking_status)}</td><td>${esc(r.approval_status||'—')}</td><td>${can('document_controller')?`<div class="planning-actions">${!r.actual_delivery_date?`<button class="btn secondary del-reschedule" data-id="${r.id}">Reschedule</button><button class="btn primary del-record" data-id="${r.id}">Record Delivery</button>`:(can('admin')?`<button class="btn secondary del-reopen" data-id="${r.id}">Reopen</button>`:'')}</div>`:''}</td></tr>`).join(''):'<tr><td colspan="10" class="muted">No deliverables.</td></tr>';document.querySelectorAll('.del-reschedule').forEach(b=>b.onclick=()=>reschedule(b.dataset.id));document.querySelectorAll('.del-record').forEach(b=>b.onclick=()=>recordDelivery(b.dataset.id));document.querySelectorAll('.del-reopen').forEach(b=>b.onclick=()=>reopen(b.dataset.id))}
function renderCalendar(){const list=rows.filter(r=>!r.actual_delivery_date).sort((a,b)=>String(a.current_due_date).localeCompare(String(b.current_due_date)));$('calendarList').innerHTML=list.length?list.map(r=>`<div class="calendar-row"><strong>${fmt(r.current_due_date)}</strong><div><strong>${esc(r.document_number||r.deliverable_title)}</strong><div class="plan-sub">${esc(r.plan_code)} · ${esc(r.discipline_code||'—')}</div></div><div>${chip(r.tracking_status)}</div><div>${r.plan_variance_days?`${r.plan_variance_days>0?'+':''}${r.plan_variance_days} days vs baseline`:'Baseline unchanged'}</div></div>`).join(''):'<div class="muted">No open deliverables.</div>'}
function toggleParent(){$('parentPlanLabel').classList.toggle('hidden',$('planType').value!=='TIDP')}
async function createPlan(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;const payload={p_plan_type:$('planType').value,p_plan_code:$('planCode').value,p_plan_name:$('planName').value,p_parent_plan_id:$('planType').value==='TIDP'?($('parentPlan').value||null):null,p_organization_code:$('planOrg').value||null,p_description:$('planDesc').value||null};const {error}=await supabase.rpc('create_information_delivery_plan',payload);btn.disabled=false;if(error)return toast(error.message,true);toast('Delivery plan created');e.target.reset();toggleParent();await loadAll()}
function fillFromDrawing(){const d=drawings.find(x=>x.id===$('delDrawing').value);if(!d)return;$('delTitle').value=d.title||'';$('delDiscipline').value=d.discipline_code||'';$('delDocType').value=d.document_type_code||''}
async function createDeliverable(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;const {error}=await supabase.rpc('add_information_deliverable',{p_plan_id:$('delPlan').value,p_deliverable_title:$('delTitle').value,p_baseline_due_date:$('delBaseline').value,p_drawing_id:$('delDrawing').value||null,p_discipline_code:$('delDiscipline').value||null,p_document_type_code:$('delDocType').value||null,p_responsible_organization_code:$('delOrg').value||null,p_notes:$('delNotes').value||null});btn.disabled=false;if(error)return toast(error.message,true);toast('Deliverable added to plan');e.target.reset();await loadAll()}
async function reschedule(id){const row=rows.find(x=>x.id===id);const date=prompt(`New planned delivery date for ${row?.document_number||row?.deliverable_title}:`,row?.current_due_date||'');if(!date)return;const reason=prompt('Reason for changing the planned date:');if(!reason)return;const {error}=await supabase.rpc('reschedule_information_deliverable',{p_deliverable_id:id,p_new_due_date:date,p_reason:reason});if(error)return toast(error.message,true);toast('Planned date updated; baseline preserved');await loadAll()}
async function recordDelivery(id){const row=rows.find(x=>x.id===id);let revisions=[];if(row?.drawing_id){const {data}=await supabase.from('drawing_revisions').select('id,revision,filename,created_at').eq('drawing_id',row.drawing_id).order('sequence_no',{ascending:false});revisions=data||[]}const date=prompt('Actual delivery date:',new Date().toISOString().slice(0,10));if(!date)return;let revId=null;if(revisions.length){const choices=revisions.slice(0,15).map((r,i)=>`${i+1}: ${r.revision} — ${r.filename}`).join('\n');const pick=prompt(`Revision delivered (enter number, or leave blank):\n${choices}`);if(pick){const r=revisions[Number(pick)-1];if(!r)return toast('Invalid revision selection',true);revId=r.id}}const notes=prompt('Delivery note (optional):','')||null;const {error}=await supabase.rpc('record_information_delivery',{p_deliverable_id:id,p_actual_delivery_date:date,p_revision_id:revId,p_notes:notes});if(error)return toast(error.message,true);toast('Actual delivery recorded');await loadAll()}
async function reopen(id){const reason=prompt('Admin reason for reopening this delivery record:');if(!reason)return;const {error}=await supabase.rpc('reopen_information_deliverable',{p_deliverable_id:id,p_reason:reason});if(error)return toast(error.message,true);toast('Deliverable reopened');await loadAll()}
bootstrap();
}
