import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.DLM_CONFIG;
if(cfg){
  const sb=createClient(cfg.url,cfg.key),$=id=>document.getElementById(id);
  let role='viewer';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const toast=(m,e=false)=>{const t=$('toast');if(!t)return;t.textContent=m;t.className=`toast show ${e?'error':'success'}`;clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast',4500)};
  const canAdmin=()=>role==='admin';
  function addStyles(){if($('prodFinishStyles'))return;const s=document.createElement('style');s.id='prodFinishStyles';s.textContent=`
  .restore-modal-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.46);display:flex;align-items:center;justify-content:center;z-index:9999;padding:20px}.restore-modal{background:#fff;max-width:720px;width:100%;border-radius:14px;padding:20px;box-shadow:0 24px 80px rgba(0,0,0,.25)}.restore-counts{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.restore-count{padding:10px;border:1px solid #e5eaf0;border-radius:8px}.restore-count span{display:block;font-size:11px;color:#6f7a8b}.restore-count strong{font-size:20px}.prod-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:16px 0}.prod-kpi{padding:14px}.prod-kpi span{display:block;font-size:11px;color:#748094}.prod-kpi strong{font-size:22px}.backup-row{grid-template-columns:1fr auto auto auto!important}.prod-warning{padding:10px 12px;background:#fff4df;border-radius:8px;font-size:12px}.prod-filterbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.prod-filterbar input,.prod-filterbar select{min-width:150px}@media(max-width:900px){.prod-kpis{grid-template-columns:1fr 1fr}.restore-counts{grid-template-columns:1fr 1fr}}@media(max-width:620px){.prod-kpis,.restore-counts{grid-template-columns:1fr}.backup-row{grid-template-columns:1fr!important}}
  `;document.head.appendChild(s)}
  function showRestoreModal(preview,onConfirm){document.querySelector('.restore-modal-backdrop')?.remove();const snap=preview.snapshot||{},cur=preview.current||{};const keys=['drawings','revisions','approvals','plans','deliverables','events','date_changes','saved_views'];const b=document.createElement('div');b.className='restore-modal-backdrop';b.innerHTML=`<div class="restore-modal"><div class="panel-head"><div><h3>Restore Backup Snapshot</h3><p class="muted">${esc(preview.backup_name)} · ${esc(preview.created_at||'')}</p></div><button class="btn secondary" id="closeRestoreModal">Close</button></div><div class="prod-warning"><strong>Destructive restore:</strong> operational application data will be replaced by this snapshot. A new automatic pre-restore backup will be created first. Users, roles, lookup code lists, audit history and backup history are preserved.</div><div class="restore-counts">${keys.map(k=>`<div class="restore-count"><span>${esc(k.replaceAll('_',' '))}</span><strong>${Number(snap[k]||0)}</strong><div class="tiny muted">current: ${Number(cur[k]||0)}</div></div>`).join('')}</div><label>Type <strong>RESTORE</strong> to continue<input id="restoreConfirmText" autocomplete="off" /></label><div class="suite-actions" style="margin-top:14px"><button id="runRestoreBtn" class="btn danger-btn" disabled>Restore Snapshot</button><button id="cancelRestoreBtn" class="btn secondary">Cancel</button></div></div>`;document.body.appendChild(b);const inp=$('restoreConfirmText'),run=$('runRestoreBtn');inp.oninput=()=>run.disabled=inp.value.trim().toUpperCase()!=='RESTORE';const close=()=>b.remove();$('closeRestoreModal').onclick=close;$('cancelRestoreBtn').onclick=close;b.onclick=e=>{if(e.target===b)close()};run.onclick=async()=>{run.disabled=true;run.textContent='Restoring…';await onConfirm(inp.value.trim());};}
  async function previewRestore(id){const {data,error}=await sb.rpc('admin_preview_backup_restore',{p_backup_id:id});if(error)return toast(error.message,true);showRestoreModal(data,async confirmText=>{const {data:r,error:e}=await sb.rpc('admin_restore_backup_snapshot',{p_backup_id:id,p_confirmation:confirmText});if(e){toast(e.message,true);document.querySelector('.restore-modal-backdrop')?.remove();return}toast(`Backup restored. Safety backup: ${r?.pre_restore_backup_id||'created'}`);setTimeout(()=>location.reload(),900)});}
  function wireBackupRestore(){if(!canAdmin())return;const list=$('backupList');if(!list)return;list.querySelectorAll('.backup-row').forEach(row=>{if(row.querySelector('.restore-backup'))return;const dl=row.querySelector('.dl-backup');const id=dl?.dataset.id;if(!id)return;const b=document.createElement('button');b.className='btn secondary restore-backup';b.textContent='Preview / Restore';b.dataset.id=id;b.onclick=()=>previewRestore(id);row.insertBefore(b,row.lastElementChild)});}
  function observeBackups(){const wait=()=>{const list=$('backupList');if(!list)return setTimeout(wait,300);wireBackupRestore();new MutationObserver(wireBackupRestore).observe(list,{childList:true,subtree:true});};wait()}
  async function injectDeliveryKpis(){const page=$('dashboardPage');if(!page)return;if(!$('prodDeliveryKpis')){const el=document.createElement('div');el.id='prodDeliveryKpis';el.className='prod-kpis';el.innerHTML=`<div class="panel prod-kpi"><span>Information Deliverables</span><strong id="prodDelTotal">—</strong></div><div class="panel prod-kpi"><span>Due Next 7 Days</span><strong id="prodDelSoon">—</strong></div><div class="panel prod-kpi"><span>Open Overdue</span><strong id="prodDelOverdue">—</strong></div><div class="panel prod-kpi"><span>On-time Delivery</span><strong id="prodDelOnTime">—</strong></div><div class="panel prod-kpi"><span>Active TIDPs</span><strong id="prodTidps">—</strong></div>`;page.querySelector('#advancedDashboard')?.before(el)||page.querySelector('.stats-grid')?.after(el)}const [{data:rows,error},{data:plans,error:pe}]=await Promise.all([sb.from('information_delivery_register_v').select('tracking_status,current_due_date,actual_delivery_date'),sb.from('information_delivery_plans').select('plan_type,status')]);if(error||pe)return;const r=rows||[],delivered=r.filter(x=>x.actual_delivery_date),on=delivered.filter(x=>['Delivered On Time','Delivered Early'].includes(x.tracking_status)).length;$('prodDelTotal').textContent=r.length;$('prodDelSoon').textContent=r.filter(x=>x.tracking_status==='Due Soon'||x.tracking_status==='Due Today').length;$('prodDelOverdue').textContent=r.filter(x=>x.tracking_status==='Overdue').length;$('prodDelOnTime').textContent=delivered.length?`${Math.round(on/delivered.length*100)}%`:'—';$('prodTidps').textContent=(plans||[]).filter(x=>x.plan_type==='TIDP'&&x.status==='active').length;}
  function polishPlanningFilters(){const wait=()=>{const pane=$('planDeliverables');if(!pane)return setTimeout(wait,300);if($('prodPlanningFilters'))return;const head=pane.querySelector('.panel .panel-head');if(!head)return;const bar=document.createElement('div');bar.id='prodPlanningFilters';bar.className='prod-filterbar';bar.innerHTML=`<input id="prodPlanSearch" placeholder="Search deliverable / drawing"/><select id="prodTrackFilter"><option value="">All tracking statuses</option><option>On Track</option><option>Due Soon</option><option>Due Today</option><option>Overdue</option><option>Delivered Early</option><option>Delivered On Time</option><option>Delivered Late</option></select><button id="prodClearPlanFilters" class="btn secondary">Clear</button>`;head.after(bar);const apply=()=>{const q=$('prodPlanSearch').value.trim().toLowerCase(),st=$('prodTrackFilter').value;document.querySelectorAll('#deliverableBody tr').forEach(tr=>{const txt=tr.textContent.toLowerCase();tr.style.display=(!q||txt.includes(q))&&(!st||tr.textContent.includes(st))?'':'none'})};$('prodPlanSearch').oninput=apply;$('prodTrackFilter').onchange=apply;$('prodClearPlanFilters').onclick=()=>{$('prodPlanSearch').value='';$('prodTrackFilter').value='';apply()};new MutationObserver(apply).observe($('deliverableBody'),{childList:true,subtree:true});};wait()}
  function hardenWorkflowUi(){const wait=()=>{const panel=$('workflowPanel');if(!panel)return setTimeout(wait,300);const sync=()=>{const pending=panel.querySelector('.workflow-chip.pending');const submit=$('submitApprovalBtn');if(submit){submit.disabled=!!pending;submit.title=pending?'A request is already pending for this drawing':'';submit.textContent=pending?'Approval Pending':'Submit for Approval'}};sync();new MutationObserver(sync).observe(panel,{childList:true,subtree:true});};wait()}
  async function init(){addStyles();const {data:{session}}=await sb.auth.getSession();if(!session)return;const {data:r}=await sb.rpc('current_user_role');role=r||'viewer';observeBackups();polishPlanningFilters();hardenWorkflowUi();await injectDeliveryKpis();window.addEventListener('focus',()=>injectDeliveryKpis());}
  setTimeout(()=>init().catch(e=>console.error('Production finish module:',e)),350);
}
